### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Kedebao_ch)
add_subdirectory(Kedebao_chContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "CMakePresets.json"
        "CMakeUserPresets.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Kedebao_chplugin
    Kedebao_chContentplugin
    QtQuickDesignerComponents)