### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Kedebao_ch)
add_subdirectory(Kedebao_chContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Kedebao_chplugin
    Kedebao_chContentplugin)